# Generated by Django 5.1.7 on 2025-03-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_spare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='is_strike',
            field=models.BooleanField(default=False),
        ),
    ]
