# Generated by Django 5.1.7 on 2025-03-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_score_is_spare_score_is_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_team',
            field=models.CharField(choices=[('keith', 'Keith’s Team'), ('opponent', 'Opponent Team')], default='keith', max_length=10),
        ),
    ]
